// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripSplitBK.Data;

#nullable disable

namespace TripSplitBK.Migrations
{
    [DbContext(typeof(TripSplitDbContext))]
    [Migration("20260528154013_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripSplitBK.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("TripId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "cat_1",
                            CategoryName = "餐飲",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🍜",
                            IsActive = true,
                            Note = "預設分類",
                            TripId = "trip_default"
                        },
                        new
                        {
                            CategoryId = "cat_2",
                            CategoryName = "早餐",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🍳",
                            IsActive = true,
                            Note = "自訂分類",
                            TripId = "trip_default"
                        },
                        new
                        {
                            CategoryId = "cat_3",
                            CategoryName = "門票",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🎟",
                            IsActive = true,
                            Note = "自訂分類",
                            TripId = "trip_default"
                        },
                        new
                        {
                            CategoryId = "cat_4",
                            CategoryName = "交通",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🚆",
                            IsActive = true,
                            Note = "預設分類",
                            TripId = "trip_default"
                        },
                        new
                        {
                            CategoryId = "cat_5",
                            CategoryName = "住宿",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🏨",
                            IsActive = true,
                            Note = "預設分類",
                            TripId = "trip_default"
                        },
                        new
                        {
                            CategoryId = "cat_6",
                            CategoryName = "購物",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🛍",
                            IsActive = true,
                            Note = "預設分類",
                            TripId = "trip_default"
                        });
                });

            modelBuilder.Entity("TripSplitBK.Models.ExchangeRate", b =>
                {
                    b.Property<string>("RateId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RateToTwd")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TargetCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("RateId");

                    b.ToTable("exchange_rates");

                    b.HasData(
                        new
                        {
                            RateId = "rate_seed_jpy",
                            BaseCurrency = "JPY",
                            FetchedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = "seed",
                            RateToTwd = 0.2185m,
                            TargetCurrency = "TWD"
                        },
                        new
                        {
                            RateId = "rate_seed_usd",
                            BaseCurrency = "USD",
                            FetchedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = "seed",
                            RateToTwd = 32.1m,
                            TargetCurrency = "TWD"
                        },
                        new
                        {
                            RateId = "rate_seed_krw",
                            BaseCurrency = "KRW",
                            FetchedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = "seed",
                            RateToTwd = 0.0235m,
                            TargetCurrency = "TWD"
                        },
                        new
                        {
                            RateId = "rate_seed_eur",
                            BaseCurrency = "EUR",
                            FetchedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = "seed",
                            RateToTwd = 34.8m,
                            TargetCurrency = "TWD"
                        },
                        new
                        {
                            RateId = "rate_seed_thb",
                            BaseCurrency = "THB",
                            FetchedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = "seed",
                            RateToTwd = 0.88m,
                            TargetCurrency = "TWD"
                        },
                        new
                        {
                            RateId = "rate_seed_twd",
                            BaseCurrency = "TWD",
                            FetchedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Provider = "seed",
                            RateToTwd = 1m,
                            TargetCurrency = "TWD"
                        });
                });

            modelBuilder.Entity("TripSplitBK.Models.Expense", b =>
                {
                    b.Property<string>("ExpenseId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("AmountOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountTwd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExchangeRateToTwd")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ExpenseDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginalCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PayerMemberName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SplitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExpenseId");

                    b.HasIndex("TripId");

                    b.ToTable("expenses");
                });

            modelBuilder.Entity("TripSplitBK.Models.ExpenseParticipant", b =>
                {
                    b.Property<string>("ParticipantId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ShareAmountTwd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SharePercentage")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ParticipantId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("expense_participants");
                });

            modelBuilder.Entity("TripSplitBK.Models.ExpenseReceipt", b =>
                {
                    b.Property<string>("ReceiptId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReceiptId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("expense_receipts");
                });

            modelBuilder.Entity("TripSplitBK.Models.Member", b =>
                {
                    b.Property<string>("MemberId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AvatarText")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailOrNote")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MemberId");

                    b.HasIndex("TripId");

                    b.ToTable("members");

                    b.HasData(
                        new
                        {
                            MemberId = "mem_1",
                            AvatarText = "D",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailOrNote = "發起人",
                            IsActive = true,
                            MemberName = "Dustin",
                            TripId = "trip_default"
                        },
                        new
                        {
                            MemberId = "mem_2",
                            AvatarText = "A",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailOrNote = "旅伴",
                            IsActive = true,
                            MemberName = "Amy",
                            TripId = "trip_default"
                        },
                        new
                        {
                            MemberId = "mem_3",
                            AvatarText = "B",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailOrNote = "旅伴",
                            IsActive = true,
                            MemberName = "Ben",
                            TripId = "trip_default"
                        },
                        new
                        {
                            MemberId = "mem_4",
                            AvatarText = "C",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailOrNote = "旅伴",
                            IsActive = true,
                            MemberName = "Cindy",
                            TripId = "trip_default"
                        });
                });

            modelBuilder.Entity("TripSplitBK.Models.PaymentMethod", b =>
                {
                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("TripId");

                    b.ToTable("payment_methods");

                    b.HasData(
                        new
                        {
                            PaymentMethodId = "pay_1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "💵",
                            IsActive = true,
                            Note = "預設方式",
                            PaymentMethodName = "現金",
                            TripId = "trip_default"
                        },
                        new
                        {
                            PaymentMethodId = "pay_2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "💳",
                            IsActive = true,
                            Note = "信用卡",
                            PaymentMethodName = "Visa",
                            TripId = "trip_default"
                        },
                        new
                        {
                            PaymentMethodId = "pay_3",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "📱",
                            IsActive = true,
                            Note = "行動支付",
                            PaymentMethodName = "LINE Pay",
                            TripId = "trip_default"
                        },
                        new
                        {
                            PaymentMethodId = "pay_4",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🚇",
                            IsActive = true,
                            Note = "交通卡",
                            PaymentMethodName = "Suica",
                            TripId = "trip_default"
                        });
                });

            modelBuilder.Entity("TripSplitBK.Models.Trip", b =>
                {
                    b.Property<string>("TripId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("TripName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TripId");

                    b.ToTable("trips");

                    b.HasData(
                        new
                        {
                            TripId = "trip_default",
                            BaseCurrency = "TWD",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "Dustin",
                            IsArchived = false,
                            TripName = "東京五日遊",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TripSplitBK.Models.Category", b =>
                {
                    b.HasOne("TripSplitBK.Models.Trip", "Trip")
                        .WithMany("Categories")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripSplitBK.Models.Expense", b =>
                {
                    b.HasOne("TripSplitBK.Models.Trip", "Trip")
                        .WithMany("Expenses")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripSplitBK.Models.ExpenseParticipant", b =>
                {
                    b.HasOne("TripSplitBK.Models.Expense", "Expense")
                        .WithMany("Participants")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("TripSplitBK.Models.ExpenseReceipt", b =>
                {
                    b.HasOne("TripSplitBK.Models.Expense", "Expense")
                        .WithMany("Receipts")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("TripSplitBK.Models.Member", b =>
                {
                    b.HasOne("TripSplitBK.Models.Trip", "Trip")
                        .WithMany("Members")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripSplitBK.Models.PaymentMethod", b =>
                {
                    b.HasOne("TripSplitBK.Models.Trip", "Trip")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripSplitBK.Models.Expense", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("TripSplitBK.Models.Trip", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Expenses");

                    b.Navigation("Members");

                    b.Navigation("PaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
